### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by ovninosa** [Mati20041/spring-session-jpa-repository#1]
Mati,

Hello, I recently implement your code and work OK (the session over DB) but I cannot get working the session timeout. 

Like this over the web.xml:

```
    <session-config>
        <session-timeout>1</session-timeout>
        <cookie-config>
            <name>SESSION</name>
            <http-only>true</http-only>
        </cookie-config>
        <tracking-mode>COOKIE</tracking-mode>
    </session-config>
```

Or even in my login success handler:

```
    public void onAuthenticationSuccess(HttpServletRequest request, HttpServletResponse response, Authentication authentication) throws IOException {
        handle(request, response, authentication);
        HttpSession session = request.getSession(false);

        if (session != null) {
            session.setMaxInactiveInterval(60 * 1);
        }
        clearAuthenticationAttributes(request);
    }
```

On the session service:

```
    @Override
    public ExpiringSession createSession() {
        ExpiringSession result = new MapSession();     

        result.setMaxInactiveIntervalInSeconds(60);

        return result;
    }
```

I think result.setMaxInactiveIntervalInSeconds(60); is the correct way, but it doesn't work. 

Do you have any idea about this?
Thanks

**Comment by Mati20041** [comment]
Hello!

Yes, there wasn't check for a session expiration. I have added it in the newest commit. Enjoy ;)

In SecurityConfiguration.java :

```
    return new JPASessionRepository(10); //max time in seconds of session idle
```

in JPASessionRepository.java :

```
    public ExpiringSession getSession(String id) {
        SessionEntity sessionEntity = springSessionRepository.findOne(id);
        ExpiringSession saved = sessionEntity == null ? null : convertToSession(sessionEntity);
        if(saved == null) {
            return null;
        }
        if(saved.isExpired()) {
            delete(saved.getId());
            return null;
        }
        return saved;
    }
```

**Comment by ovninosa** [comment]
Mati, thankssssss for your time and effort.

I recently added your new code but the sessions never get timeout. I just wait for about 1 minute and hit refresh, but the session is still alive.
Do you have any idea?

Thanks again

**Comment by Mati20041** [comment]
Look at the changes in JPASessionRepository in the newest commit ;) Clone again my project and check if it works (session timeout is setted to 10 seconds).

**Comment by ovninosa** [comment]
Mati, when I wrote my last message I already implement the new code.
The code doesn't work :(

Thanks

**Comment by Mati20041** [comment]
Try these steps:
1. clone again my project
2. with bash or cmd go to folder and run `./gradlew clean bootRun` (for windows `gradlew.bat clean bootRun`)
3. In your browser go to localhost:8080
4. login with mati:qwerty
5. browser should display "Huray! Rerfresh page!". Refresh page.
6. browser now should display "Huray! You made it!"
7. wait more than 10 seconds and refresh
8. now browser should display login page. That means your session has expired.

**Comment by ovninosa** [comment]
Mati, thanks again, I will try it later.
In any case I think the result will be the same because I compared your new commit with my current project and merged with a comparison Tool.

Do you have already tested this functionality? 

Thanks!!

**Comment by ovninosa** [comment]
Hey mati!
Any news on this?

Thanks

**Comment by Mati20041** [comment]
Hey,

Did you try flow that I had told you?

**Comment by ovninosa** [comment]
@Mati20041 Mati, sorry for the delayed answer, the code works ok, when I refresh the site the session are gone.

Just one more question, there is a way to clear the session table? because when the session is lost the registry is still there. 
Something like a cron work o anything like this?

Thanks!

**Comment by Mati20041** [comment]
@javenosa 

The best option is to use @Schedule annotation on method which will clear DB from old and unused session.
